# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jyshi/yela

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jyshi/yela

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jyshi/yela/CMakeFiles /home/jyshi/yela/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jyshi/yela/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named yela

# Build rule for target.
yela: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 yela
.PHONY : yela

# fast build rule for target.
yela/fast:
	$(MAKE) -f CMakeFiles/yela.dir/build.make CMakeFiles/yela.dir/build
.PHONY : yela/fast

src/interface.o: src/interface.cc.o

.PHONY : src/interface.o

# target to build an object file
src/interface.cc.o:
	$(MAKE) -f CMakeFiles/yela.dir/build.make CMakeFiles/yela.dir/src/interface.cc.o
.PHONY : src/interface.cc.o

src/interface.i: src/interface.cc.i

.PHONY : src/interface.i

# target to preprocess a source file
src/interface.cc.i:
	$(MAKE) -f CMakeFiles/yela.dir/build.make CMakeFiles/yela.dir/src/interface.cc.i
.PHONY : src/interface.cc.i

src/interface.s: src/interface.cc.s

.PHONY : src/interface.s

# target to generate assembly for a file
src/interface.cc.s:
	$(MAKE) -f CMakeFiles/yela.dir/build.make CMakeFiles/yela.dir/src/interface.cc.s
.PHONY : src/interface.cc.s

src/log.o: src/log.cc.o

.PHONY : src/log.o

# target to build an object file
src/log.cc.o:
	$(MAKE) -f CMakeFiles/yela.dir/build.make CMakeFiles/yela.dir/src/log.cc.o
.PHONY : src/log.cc.o

src/log.i: src/log.cc.i

.PHONY : src/log.i

# target to preprocess a source file
src/log.cc.i:
	$(MAKE) -f CMakeFiles/yela.dir/build.make CMakeFiles/yela.dir/src/log.cc.i
.PHONY : src/log.cc.i

src/log.s: src/log.cc.s

.PHONY : src/log.s

# target to generate assembly for a file
src/log.cc.s:
	$(MAKE) -f CMakeFiles/yela.dir/build.make CMakeFiles/yela.dir/src/log.cc.s
.PHONY : src/log.cc.s

src/main.o: src/main.cc.o

.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) -f CMakeFiles/yela.dir/build.make CMakeFiles/yela.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) -f CMakeFiles/yela.dir/build.make CMakeFiles/yela.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) -f CMakeFiles/yela.dir/build.make CMakeFiles/yela.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/network.o: src/network.cc.o

.PHONY : src/network.o

# target to build an object file
src/network.cc.o:
	$(MAKE) -f CMakeFiles/yela.dir/build.make CMakeFiles/yela.dir/src/network.cc.o
.PHONY : src/network.cc.o

src/network.i: src/network.cc.i

.PHONY : src/network.i

# target to preprocess a source file
src/network.cc.i:
	$(MAKE) -f CMakeFiles/yela.dir/build.make CMakeFiles/yela.dir/src/network.cc.i
.PHONY : src/network.cc.i

src/network.s: src/network.cc.s

.PHONY : src/network.s

# target to generate assembly for a file
src/network.cc.s:
	$(MAKE) -f CMakeFiles/yela.dir/build.make CMakeFiles/yela.dir/src/network.cc.s
.PHONY : src/network.cc.s

src/node.o: src/node.cc.o

.PHONY : src/node.o

# target to build an object file
src/node.cc.o:
	$(MAKE) -f CMakeFiles/yela.dir/build.make CMakeFiles/yela.dir/src/node.cc.o
.PHONY : src/node.cc.o

src/node.i: src/node.cc.i

.PHONY : src/node.i

# target to preprocess a source file
src/node.cc.i:
	$(MAKE) -f CMakeFiles/yela.dir/build.make CMakeFiles/yela.dir/src/node.cc.i
.PHONY : src/node.cc.i

src/node.s: src/node.cc.s

.PHONY : src/node.s

# target to generate assembly for a file
src/node.cc.s:
	$(MAKE) -f CMakeFiles/yela.dir/build.make CMakeFiles/yela.dir/src/node.cc.s
.PHONY : src/node.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... yela"
	@echo "... edit_cache"
	@echo "... src/interface.o"
	@echo "... src/interface.i"
	@echo "... src/interface.s"
	@echo "... src/log.o"
	@echo "... src/log.i"
	@echo "... src/log.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/network.o"
	@echo "... src/network.i"
	@echo "... src/network.s"
	@echo "... src/node.o"
	@echo "... src/node.i"
	@echo "... src/node.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

